
package test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimulatorService", targetNamespace = "http://test/", wsdlLocation = "http://localhost:8080/Symulacja/Simulator?wsdl")
public class SimulatorService
    extends Service
{

    private final static URL SIMULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMULATORSERVICE_EXCEPTION;
    private final static QName SIMULATORSERVICE_QNAME = new QName("http://test/", "SimulatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Symulacja/Simulator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMULATORSERVICE_WSDL_LOCATION = url;
        SIMULATORSERVICE_EXCEPTION = e;
    }

    public SimulatorService() {
        super(__getWsdlLocation(), SIMULATORSERVICE_QNAME);
    }

    public SimulatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMULATORSERVICE_QNAME, features);
    }

    public SimulatorService(URL wsdlLocation) {
        super(wsdlLocation, SIMULATORSERVICE_QNAME);
    }

    public SimulatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMULATORSERVICE_QNAME, features);
    }

    public SimulatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimulatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Simulator
     */
    @WebEndpoint(name = "SimulatorPort")
    public Simulator getSimulatorPort() {
        return super.getPort(new QName("http://test/", "SimulatorPort"), Simulator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Simulator
     */
    @WebEndpoint(name = "SimulatorPort")
    public Simulator getSimulatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test/", "SimulatorPort"), Simulator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMULATORSERVICE_EXCEPTION!= null) {
            throw SIMULATORSERVICE_EXCEPTION;
        }
        return SIMULATORSERVICE_WSDL_LOCATION;
    }

}
