
package test;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Simulator", targetNamespace = "http://test/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Simulator {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendError", targetNamespace = "http://test/", className = "test.SendError")
    @ResponseWrapper(localName = "sendErrorResponse", targetNamespace = "http://test/", className = "test.SendErrorResponse")
    public void sendError(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "start", targetNamespace = "http://test/", className = "test.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://test/", className = "test.StartResponse")
    public void start();

    /**
     * 
     * @param strefa
     */
    @WebMethod
    @RequestWrapper(localName = "increment", targetNamespace = "http://test/", className = "test.Increment")
    @ResponseWrapper(localName = "incrementResponse", targetNamespace = "http://test/", className = "test.IncrementResponse")
    public void increment(
        @WebParam(name = "strefa", targetNamespace = "")
        int strefa);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://test/", className = "test.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://test/", className = "test.SendMessageResponse")
    public void sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Place> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Place> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        boolean arg2);

    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "check", targetNamespace = "http://test/", className = "test.Check")
    @ResponseWrapper(localName = "checkResponse", targetNamespace = "http://test/", className = "test.CheckResponse")
    public void check();

    /**
     * 
     * @param strefa
     */
    @WebMethod
    @RequestWrapper(localName = "decrement", targetNamespace = "http://test/", className = "test.Decrement")
    @ResponseWrapper(localName = "decrementResponse", targetNamespace = "http://test/", className = "test.DecrementResponse")
    public void decrement(
        @WebParam(name = "strefa", targetNamespace = "")
        int strefa);

}
